### ISSUE TITLE
Unable to build on FreeBSD 14.0

### ISSUE THREAD

**Issue by hhartzer** [litehtml/litebrowser-linux#19]
I make it to this point. Thank you!

```
/usr/include/c++/v1/__utility/pair.h:74:5: error: the parameter for this explicitly-defaulted copy constructor is const, but a member or base requires it to be non-const
    pair(pair const&) = default;
    ^
/usr/include/c++/v1/map:739:16: note: in instantiation of template class 'std::pair<const std::string, cairo_surface_wrapper>' requested here
    value_type __cc_;
               ^
litebrowser-linux/litehtml/containers/cairo/cairo_images_cache.h:64:11: note: in instantiation of template class 'std::__value_type<std::string, cairo_surface_wrapper>' requested here
                if(iter != m_images.end())
                        ^
In file included from litebrowser-linux/src/main.cpp:1:
In file included from litebrowser-linux/src/globals.h:3:
In file included from /usr/include/c++/v1/fstream:186:
In file included from /usr/include/c++/v1/__locale:18:
In file included from /usr/include/c++/v1/mutex:191:
In file included from /usr/include/c++/v1/__memory/shared_ptr.h:31:
/usr/include/c++/v1/__memory/unique_ptr.h:65:5: warning: delete called on non-final 'litehtml::line_box_item' that has virtual functions but non-virtual destructor [-Wdelete-non-abstract-non-virtual-dtor]
    delete __ptr;
    ^
/usr/include/c++/v1/__memory/unique_ptr.h:297:7: note: in instantiation of member function 'std::default_delete<litehtml::line_box_item>::operator()' requested here
      __ptr_.second()(__tmp);
      ^
/usr/include/c++/v1/__memory/unique_ptr.h:263:75: note: in instantiation of member function 'std::unique_ptr<litehtml::line_box_item>::reset' requested here
  _LIBCPP_INLINE_VISIBILITY _LIBCPP_CONSTEXPR_SINCE_CXX23 ~unique_ptr() { reset(); }
                                                                          ^
/usr/include/c++/v1/__memory/allocator_traits.h:325:15: note: in instantiation of member function 'std::unique_ptr<litehtml::line_box_item>::~unique_ptr' requested here
        __p->~_Tp();
              ^
/usr/include/c++/v1/list:739:34: note: in instantiation of function template specialization 'std::allocator_traits<std::allocator<std::__list_node<std::unique_ptr<litehtml::line_box_item>, void *>>>::destroy<std::unique_ptr<litehtml::line_box_item>, void, void>' requested here
            __node_alloc_traits::destroy(__na, _VSTD::addressof(__np->__value_));
                                 ^
/usr/include/c++/v1/list:720:3: note: in instantiation of member function 'std::__list_imp<std::unique_ptr<litehtml::line_box_item>, std::allocator<std::unique_ptr<litehtml::line_box_item>>>::clear' requested here
  clear();
  ^
/usr/include/c++/v1/list:811:28: note: in instantiation of member function 'std::__list_imp<std::unique_ptr<litehtml::line_box_item>, std::allocator<std::unique_ptr<litehtml::line_box_item>>>::~__list_imp' requested here
class _LIBCPP_TEMPLATE_VIS list
                           ^
2 warnings and 1 error generated.
*** Error code 1

Stop.
```

**Comment by risicle** [comment]
Same issue on macos 12 x86_64, Clang 16.0.6

**Comment by casesolved-co-uk** [comment]
> Same issue on macos 12 x86_64, Clang 16.0.6

gtk3 and gtk4 branches both compile on my macos 12.7.6:
Apple clang version 14.0.0 (clang-1400.0.29.202)
Target: x86_64-apple-darwin21.6.0
